name: glo_mobile
description: Natywna aplikacja Grudziądzkiej Ligi Orlikowej na Androida i iOS.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.3
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
